### ISSUE TITLE
Incorrect formatting: Keywords are highlighted as keywords even when they are part of a larger word

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#10]
Ref. `Bodies to map` script, line 3
![Untitled](https://user-images.githubusercontent.com/4382539/69687227-050b4a00-1077-11ea-9c51-94a2c97481e6.png)
reportTerra***for***mables.

**Comment by Tkael** [comment]
Note: This does not appear to occur for all keywords. It only occurs for the subset of key words that are defined with `Predicate statement` rules.

**Comment by richardbuckle** [comment]
LOL thanks.
