### ISSUE TITLE
Unexpected delimiter fails when the unexpected delimiter / syntax error is an extra `}`

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#11]
`{}}` seems to fail the unexpected delimiter test. One of the closing brackets `}` should be identified as an unexpected delimiter but neither is. 

In a more complete use case:
```
Module repaired
{Occasionally(2, 
    cat(OneOf(", ", "and is"), " ready for re-activation")
)}.
```
is a valid script with balanced delimiters.

```
Module repaired
{Occasionally(2, 
    cat(OneOf(", ", "and is"), " ready for re-activation")
)}}.
```
is not valid. The extra closing curly bracket in the last line is not identified as a syntax error.

**Comment by Tkael** [comment]
I would guess that what I'm seeing is essentially an unexpected delimiter in a body text region?.

**Comment by Tkael** [comment]
Adding the following rule to the `Body text` ruleset in Cottle.xshd appears to resolve the issue:
```xml
    <!-- delimiters not matched by any other rule are unexpected (i.e. a syntax error) -->
    <Rule color="UnexpectedDelimiter">
      [}]
    </Rule>
```

**Comment by richardbuckle** [comment]
Thanks. 

I've been experimenting in Cottle's own demo app (just clone [the repo](https://github.com/r3c/cottle) and build).

- `{}` is invalid for want of content, but for mere syntax highlighting we can let that slide.
- `{echo 42}` is of course valid.
- `{echo 42}}` is invalid with message: `expected 'end of file', found ''`.
- just `}` on its own is also invalid with message: `expected 'end of file', found ''`.

Those last two messages aren't very helpful but that's Cottle's problem not ours so let's not worry about that.

Your fix looks correct too. Let's roll it into beta 2. 

Are you OK to for me to delete your earlier feature branch BTW? It helped me a lot but I ended up finding it easier to amend my own branch.

**Comment by Tkael** [comment]
Agreed (on both counts).

**Comment by Tkael** [comment]
I'll probably keep a local copy of my branch for a while (just in case) but I'll delete the repo copy.

**Comment by Tkael** [comment]
Fixed by https://github.com/richardbuckle/AvalonCottle/commit/76adc0d101bcf9f1ee04ff6f80f2324c8b69b9f7
