### ISSUE TITLE
`CTRL + D` deletes the current line (we may want to disable this?)

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#2]
I'm still looking for a way to edit / configure shortcuts

**Comment by richardbuckle** [comment]
It's not readily configurable: I've examined the source code. My first reaction is let's just live with it for the first iteration and see if anyone complains. There is full undo support after all.

One mitigation might be to make it visible by adding a toolbar button for it (with tooltip).

There are ways one could disable it, the simplest being to supersede it with a do-nothing `RoutedCommand` that responds to Ctrl+D, but let's not go there yet.

[WPF Commanding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/commanding-overview)

**Comment by richardbuckle** [comment]
I've added a toolbar icon for it, to make the command known.
