### ISSUE TITLE
Code completion pops up after typing `.`, even when dealing with simple body text

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#3]
We can 
1. write a regex (allowing `{event.example}` or `{event}.example` but not a simple string literal like `event.`) and/or
2. check that the proceeding word exists in our completion library before displaying the code completion pop up.

**Comment by richardbuckle** [comment]
It's a tech demo, don't over-think it.

**Comment by Tkael** [comment]
Fair enough. :-)
