### ISSUE TITLE
Replace tabs with spaces?

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#6]
Add the following to the `ConfigfureTextEditor()` method in `MainWindow.xaml.cs` to automatically replace entered tabs with spaces?
```cs
            textEditor.TextArea.Options.ConvertTabsToSpaces = true;
            textEditor.TextArea.Options.IndentationSize = 4;
```

**Comment by richardbuckle** [comment]
It's Cottle so tabs v spaces is irrelevant.

**Comment by Tkael** [comment]
True. It'd just be something to consider as a formatting help.
