### ISSUE TITLE
Incorrect formatting: `FSD engaged` script, line 40

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#7]
![Untitled](https://user-images.githubusercontent.com/4382539/69686330-536b1980-1074-11ea-83ea-c6b71ff4776d.png)
`You` is incorrectly colored. Supposed to be colored as `Body text`, is colored as (I think) `Code`.

**Comment by Tkael** [comment]
Note: It appears that this may share a common cause with #9. Removing `||` prior to `:` in the `{if...` statement corrects the formatting.

**Comment by richardbuckle** [comment]
Thanks

**Comment by richardbuckle** [comment]
Yep fixed with #9.
