### ISSUE TITLE
Use special formatting for incomplete pairs of quotes, brackets, and paranthesis?

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#8]
Coloring incomplete bracket pairs, parenthesis pairs, and quote pairs to highlight code where there exists an incomplete pair would be very beneficial as a scripting QOL improvement. Is this viable (possibly as a round II change)?

**Comment by richardbuckle** [comment]
I've found that in general the engine is pretty forgiving as you type: for example if your being a comment with `{_` then it will color the following text as comment even though you haven't typed the closing `}` yet.

Taking Visual Studio as an example, once you have syntax coloring then unbalanced delimiters immediately become very obvious and don't need additional highlighting.

I'd say this is another "let's live with it and see how it goes".

**Comment by richardbuckle** [comment]
After playing around, I'm going to say that the engine does a good job with unbalanced delimiters and we shouldn't waste time second-guessing it.
