### ISSUE TITLE
Incorrect formatting: Various scripts, for trailing parenthesis, delimiters, etc.

### ISSUE THREAD

**Issue by Tkael** [richardbuckle/AvalonCottle#9]
`Blueprint make report` script, lines 55 & 57, is formatted as `Body text`, supposed to be `Delimiter` and `Keyword`.

**Comment by Tkael** [comment]
There also exists a very similar looking formatting issue with the `Blueprint material report`, lines 50 and 52.

**Comment by Tkael** [comment]
Also `Bodies to map` script, lines 83, 86, and 92.

**Comment by Tkael** [comment]
Also `Body atmosphere report` script, lines 53, 59, 61, 67, 69, 75, 77, 79, 86, 128-130.

**Comment by Tkael** [comment]
Also `Body mapped` script line 38.

**Comment by Tkael** [comment]
etc.

**Comment by Tkael** [comment]
Finding: This appears to be triggered as soon as `|` (from `||`) is placed prior to `:`.

This is ok.
```
    {if recommendOtherMapping: 
        {Pause(1500)}
        {F("Bodies to map")}
    }
```

This is formats incorrectly.
```
    {if recommendOtherMapping || false: 
        {Pause(1500)}
        {F("Bodies to map")}
    }
```

**Comment by richardbuckle** [comment]
Good spot: thanks.
